import groovy.json.JsonSlurperClassic

def jSonParse (def json){
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
    agent { label "master" }
    environment {
        appName = "variable"
    }
    stages {

 stage("paso 1"){

    steps{
        scripts{
            sh "echo 'hola mundo'"
        }
      }
    }
  }
  post {
    always {
        deleteDir()
         sh "echo 'fase always'"
    }
    success {
      sh "echo 'fase success'"
    }
    failure {
      sh "echo 'fase failure'"
    }
  }   
}
